"""update profile models

Revision ID: 7679fb22a026
Revises: 
Create Date: 2026-09-19 16:37:15.294692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7679fb22a026'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_user_id'), 'certifications', ['user_id'], unique=False)
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_of_study', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_user_id'), 'educations', ['user_id'], unique=False)
    op.create_table('profile_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_reviews_user_id'), 'profile_reviews', ['user_id'], unique=True)
    op.create_table('user_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_languages_user_id'), 'user_languages', ['user_id'], unique=False)
    # op.drop_table('user')
    op.add_column('experiences', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('experiences', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    op.add_column('portfolio_links', sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='other'))
    op.add_column('portfolio_links', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('projects', sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('user_profiles', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('user_profiles', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('user_profiles', sa.Column('professional_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('user_skills', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'source')
    op.drop_column('user_profiles', 'professional_summary')
    op.drop_column('user_profiles', 'phone')
    op.drop_column('user_profiles', 'email')
    op.drop_column('projects', 'repository_url')
    op.drop_column('portfolio_links', 'label')
    op.drop_column('portfolio_links', 'kind')
    op.drop_column('experiences', 'source')
    op.drop_column('experiences', 'location')
    """op.create_table('user',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('education', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('skills', sa.VARCHAR(), nullable=False),
    sa.Column('experience', sa.VARCHAR(), nullable=False),
    sa.Column('interests', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
   )""" 
    op.drop_index(op.f('ix_user_languages_user_id'), table_name='user_languages')
    op.drop_table('user_languages')
    op.drop_index(op.f('ix_profile_reviews_user_id'), table_name='profile_reviews')
    op.drop_table('profile_reviews')
    op.drop_index(op.f('ix_educations_user_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_certifications_user_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
